language: java
jdk:
- oraclejdk10
- oraclejdk9
- oraclejdk8
- openjdk10
- openjdk9
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: TctcR4AdewAI9r612gSM4+Zp5PPZvd4cCD36E+4hJLkaxA4KQHMeDL2AB5jQoLolE1vqnFr9ZUxL3pDPVSlLAMVTPEoscKk3FfuNGN6SbXLXRWPRX20agkSzqx19kkktcEAIKEMq+s02m2yBWj4xIXgq8yZgHgG1V6V6OlpHIq/hxZDJ1Hbd0VIGz77k3xLzLbksyI6Esl34LpBcPf65RFq16G/uSBePUEtPzoPrIlUp5XHblKh1MqeLxUHgEMMOoCJBXGdJ27igREcAzwP+VDSLvT9jt2cX8bQ6A3CWLrLp0FlwEXhTIAfko+On1ya4+z3R1hDr7xJ5DcwhEK7VjU4EdANu+yg3CHV6Xn2kztAorPoSVqVqnLHzN15FI8dO2RWt+LhkgXIiT8m8XuZyYRg87elJGAI8jssPCUbIpZJVTCeOlbka36aQCrj5FrwVAenBNLln5e+XjFgT9uCvrgUEK5q/gWvbLVsZbo2sq/QC4M4Xu/ePEOVsOEx9poFiHqRIn0UB0Mntf6ZIwAKdiPr2DjlaP0eiwzMhZ5iuU6Rcij6DqYCr0x3iYqGUsN0TdHQfA4DWM67H4WdIrm7Wpe5rs9VB2uCA7L9ylRwIn8dTSxMrv0IYHQOPU1S9t5N4paHUZtRt/+3iFzc4BceaosRiiQiy8ooQ0VLc/hZl8Js=
  - secure: Y/Kba67qeBAEB4neo7VLjJCbK+NuMJK64S0KBmQaNZzCQaE6rxB7aBuau0xxRUe67zxipJ2nOK8BsdGw4RmRrN3xP8FaVKeBVbx+IB6GW2V3Yso2MeQwe5XF8jn9sswFo3QbcU7j28108LWoIy+/P6LIv5eY94DeShEz0pm09bhIVutzJ2Dt/0HOtz+/j8WoGGYureSRLDIrEknOBygG4KOrGO+kwc49kKjQNiKfGNHciGhjWLj1cl3314gb7jNoXfjvyHpuocdtV6J1KFNirzJ9mncI43uhheqKv9imwwOuQ0Pm+vubxd3k5fEYm7c5STJYYvvnYf+ndUus14YObXq/rKrOHcTc16S09bMleFD79Fn8fYc+PLh+E29pBdPSHbx41CUTigywbxncGe9QxavHA2jaXz2StL3LQvzDNI7Lq68Kx9JZUiOUUWrFnU0xJf59GcEuwHhJh9s6tqaI9QFCR4FEvIu4kjWXtryPLSO2gAnNhvusyr4pS+9xvG7WSPACGKQiHk45mGDTqFK1EDyM3cU65wPoMjCYCrxZAyjF8DdE8g2ftqfeJcCeb9yPw/1n7OXvbR0ZAjAEqpYk/BSKa2485EdXtW405K2SrCV6w1ksuzsGCiPKIwOH4a/8I03nxpt3uTN3X6QY5GaGOF7vIFPy5lmC95xDND14sWs=
script:
- "./gradlew --daemon"
- "./gradlew assemble -x test --parallel"
- "./gradlew test"
- "./gradlew jacocoTestReport"
- bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
- "./gradlew sonarqube \
  -Dsonar.organization=soramitsu \
  -Dsonar.projectKey=sora-crypto-java \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=${SONAR_TOKEN}"
