language: java
jdk:
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  # CODECOV_TOKEN
  # SONAR_TOKEN
  global:
  - secure: "L+9FctZqHvS9XEDB0HhvPAPAgHemg2/Igy8gvR1e/K2aWw5FzLtL+DZpJZ8EwdlYWoc0WugN0nanihhY2knRiUPJj9cU9ztjlhKpZE3HRiMMuEPrVs2K6WalGvMLme1iT/KtAQNajIdUdORbl4wJK9D6SmVfZb0POB5b9xn+0pJmeOyOnNlNCptWVLyeuGN8gk7ofvh1CZLCNPcoUrOc9Qw/uz6/iRQokEwSXREdyUE0yhL6Y0DVn9gR0HqlciQV6Dpi6fPjjVwqKjh6TrbQYsnP0Vkx/IN4162Qw3ACphqX1iyxuHaY5ta2gNlJ+uksmfmIJSGV9hwEM+Vzmj4d4NkDH5O80SMs2vNKKFkXOnKPOLlptSYKF6hf0YI1G7REmJDTcheVh0vO8ZaUxy4if54AuQOTqL3qvYwkpEuHSgLLGXnrj0iBJ8bQm/pMN2jO1mqc6JoH0wZBvmX0VrUl4G+IggQv1gIrGeTlzhEuiLF2V6ugYQOMjgxX9GJLPtLtQAcFbzD7R69ZDsXmIP2OqyQEqUAc7pUiUNGSvIkr4c80RznBl99cczOVMBya3ciQj22brTPq8wDG2wOdyahhxuk2nHDe0ykNtBwjioHg/STiw/u6G5KqQsF+48KyPvv3Qxulo0j1u0mDIadhswdgi6kCHdvJtjF81tksp/FA3LU="

script:
- "./gradlew --daemon"
- "./gradlew assemble -x test --parallel"
- "./gradlew test"
- "./gradlew jacocoTestReport"
- "bash <(curl -s https://codecov.io/bash)"
- "./gradlew sonarqube -Dsonar.projectKey=sora-sdk -Dsonar.host.url=https://sonar.soramitsu.co.jp -Dsonar.login=${SONAR_TOKEN}"
